// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgwXV-eNug-k5m3h7dnVCZ5Ym1gb8A38',
    appId: '1:501169288172:web:d397a5c4416196048a86c9',
    messagingSenderId: '501169288172',
    projectId: 'chat-app-5e751',
    authDomain: 'chat-app-5e751.firebaseapp.com',
    storageBucket: 'chat-app-5e751.appspot.com',
    measurementId: 'G-GZ0GJSRXQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MR0k8iPwHvGlGJRgcGGio92M3Vc-5Zk',
    appId: '1:501169288172:android:8507dca0a63bbe528a86c9',
    messagingSenderId: '501169288172',
    projectId: 'chat-app-5e751',
    storageBucket: 'chat-app-5e751.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_50CtS_6GHqo71uz0Ne4XWzMypBZXsx4',
    appId: '1:501169288172:ios:1b08932897d7e4908a86c9',
    messagingSenderId: '501169288172',
    projectId: 'chat-app-5e751',
    storageBucket: 'chat-app-5e751.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_50CtS_6GHqo71uz0Ne4XWzMypBZXsx4',
    appId: '1:501169288172:ios:1b08932897d7e4908a86c9',
    messagingSenderId: '501169288172',
    projectId: 'chat-app-5e751',
    storageBucket: 'chat-app-5e751.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
